spring:
  application:
    name: book-catalog
  datasource:
    url: jdbc:postgresql://localhost:5432/book_catalog
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

